--
-- Estrutura da tabela "pais"
--

begin try drop table pais end try begin catch end catch
CREATE TABLE PAI_PAI_pais (
  PAI_nu_id int NOT NULL,
  PAI_ds_nome varchar(60) DEFAULT NULL,
  PAI_ds_sigla varchar(2) DEFAULT NULL,
  PAI_nu_bacen int DEFAULT NULL,
  PAI_bo_ativo bit DEFAULT 1
);

--a
-- Inserindo dados na tabela "pais"
--

INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (1, 'Brasil', 'BR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (2, 'Afeganistão', 'AF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (3, 'Albânia, Republica da', 'AL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (4, 'Argélia', 'DZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (5, 'Samoa Americana', 'AS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (6, 'Andorra', 'AD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (7, 'Angola', 'AO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (8, 'Anguilla', 'AI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (9, 'Antártida', 'AQ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (10, 'Antigua e Barbuda', 'AG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (11, 'Argentina', 'AR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (12, 'Armênia, Republica da', 'AM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (13, 'Aruba', 'AW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (14, 'Austrália', 'AU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (15, 'Áustria', 'AT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (16, 'Azerbaijão, Republica do', 'AZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (17, 'Bahamas, Ilhas', 'BS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (18, 'Bahrein, Ilhas', 'BH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (19, 'Bangladesh', 'BD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (20, 'Barbados', 'BB')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (21, 'Belarus, Republica da', 'BY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (22, 'Bélgica', 'BE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (23, 'Belize', 'BZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (24, 'Benin', 'BJ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (25, 'Bermudas', 'BM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (26, 'Butão', 'BT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (27, 'Bolívia', 'BO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (28, 'Bósnia-herzegovina (Republica da)', 'BA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (29, 'Botsuana', 'BW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (30, 'Bouvet, Ilha', 'BV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (31, 'Território Britânico do Oceano Indico', 'IO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (32, 'Brunei', 'BN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (33, 'Bulgária, Republica da', 'BG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (34, 'Burkina Faso', 'BF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (35, 'Burundi', 'BI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (36, 'Camboja', 'KH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (37, 'Camarões', 'CM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (38, 'Canada', 'CA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (39, 'Cabo Verde, Republica de', 'CV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (40, 'Cayman, Ilhas', 'KY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (41, 'Republica Centro-Africana', 'CF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (42, 'Chade', 'TD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (43, 'Chile', 'CL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (44, 'China, Republica Popular', 'CN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (45, 'Christmas, Ilha (Navidad)', 'CX')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (46, 'Cocos (Keeling) Ilhas', 'CC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (47, 'Colômbia', 'CO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (48, 'Comores, Ilhas', 'KM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (49, 'Congo', 'CG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (50, 'Congo, Republica Democrática do', 'CD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (51, 'Cook, Ilhas', 'CK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (52, 'Costa Rica', 'CR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (53, 'Costa do Marfim', 'CI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (54, 'Croácia (Republica da)', 'HR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (55, 'Cuba', 'CU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (56, 'Chipre', 'CY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (57, 'Tcheca, Republica', 'CZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (58, 'Dinamarca', 'DK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (59, 'Djibuti', 'DJ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (60, 'Dominica, Ilha', 'DM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (61, 'Republica Dominicana', 'DO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (62, 'Timor Leste', 'TL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (63, 'Equador', 'EC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (64, 'Egito', 'EG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (65, 'El Salvador', 'SV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (66, 'Guine-Equatorial', 'GQ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (67, 'Eritreia', 'ER')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (68, 'Estônia, Republica da', 'EE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (69, 'Etiópia', 'ET')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (70, 'Falkland (Ilhas Malvinas)', 'FK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (71, 'Feroe, Ilhas', 'FO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (72, 'Fiji', 'FJ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (73, 'Finlândia', 'FI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (74, 'Franca', 'FR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (76, 'Guiana francesa', 'GF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (77, 'Polinésia Francesa', 'PF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (78, 'Terras Austrais e Antárticas Francesas', 'TF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (79, 'Gabão', 'GA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (80, 'Gambia', 'GM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (81, 'Georgia, Republica da', 'GE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (82, 'Alemanha', 'DE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (83, 'Gana', 'GH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (84, 'Gibraltar', 'GI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (85, 'Grécia', 'GR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (86, 'Groenlândia', 'GL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (87, 'Granada', 'GD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (88, 'Guadalupe', 'GP')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (89, 'Guam', 'GU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (90, 'Guatemala', 'GT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (91, 'Guine', 'GN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (92, 'Guine-Bissau', 'GW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (93, 'Guiana', 'GY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (94, 'Haiti', 'HT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (95, 'Ilha Heard e Ilhas McDonald', 'HM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (96, 'Vaticano, Estado da Cidade do', 'VA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (97, 'Honduras', 'HN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (98, 'Hong Kong', 'HK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (99, 'Hungria, Republica da', 'HU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (100, 'Islândia', 'IS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (101, 'Índia', 'IN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (102, 'Indonésia', 'ID')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (103, 'Ira, Republica Islâmica do', 'IR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (104, 'Iraque', 'IQ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (105, 'Irlanda', 'IE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (106, 'Israel', 'IL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (107, 'Itália', 'IT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (108, 'Jamaica', 'JM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (109, 'Japão', 'JP')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (110, 'Jordânia', 'JO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (111, 'Cazaquistão, Republica do', 'KZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (112, 'Quênia', 'KE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (113, 'Kiribati', 'KI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (114, 'Coreia, Republica Popular Democrática da', 'KP')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (115, 'Coreia, Republica da', 'KR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (116, 'Kuwait', 'KW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (117, 'Quirguiz, Republica', 'KG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (118, 'Laos, Republica Popular Democrática do', 'LA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (119, 'Letônia, Republica da', 'LV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (120, 'Líbano', 'LB')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (121, 'Lesoto', 'LS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (122, 'Libéria', 'LR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (123, 'Líbia', 'LY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (124, 'Liechtenstein', 'LI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (125, 'Lituânia, Republica da', 'LT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (126, 'Luxemburgo', 'LU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (127, 'Macau', 'MO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (128, 'Macedônia do Norte', 'MK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (129, 'Madagascar', 'MG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (130, 'Malavi', 'MW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (131, 'Malásia', 'MY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (132, 'Maldivas', 'MV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (133, 'Mali', 'ML')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (134, 'Malta', 'MT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (135, 'Marshall, Ilhas', 'MH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (136, 'Martinica', 'MQ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (137, 'Mauritânia', 'MR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (138, 'Mauricio', 'MU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (139, 'Mayotte (Ilhas Francesas)', 'YT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (140, 'México', 'MX')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (141, 'Micronesia', 'FM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (142, 'Moldávia, Republica da', 'MD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (143, 'Mônaco', 'MC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (144, 'Mongólia', 'MN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (145, 'Montserrat, Ilhas', 'MS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (146, 'Marrocos', 'MA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (147, 'Moçambique', 'MZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (148, 'Mianmar (Birmânia)', 'MM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (149, 'Namíbia', 'NA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (150, 'Nauru', 'NR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (151, 'Nepal', 'NP')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (152, 'Países Baixos (Holanda)', 'NL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (154, 'Nova Caledonia', 'NC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (155, 'Nova Zelândia', 'NZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (156, 'Nicarágua', 'NI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (157, 'Níger', 'NE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (158, 'Nigéria', 'NG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (159, 'Niue, Ilha', 'NU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (160, 'Norfolk, Ilha', 'NF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (161, 'Marianas do Norte', 'MP')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (162, 'Noruega', 'NO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (163, 'Oma', 'OM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (164, 'Paquistão', 'PK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (165, 'Palau', 'PW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (166, 'Panamá', 'PA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (167, 'Papua Nova Guine', 'PG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (168, 'Paraguai', 'PY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (169, 'Peru', 'PE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (170, 'Filipinas', 'PH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (171, 'Pitcairn, Ilha', 'PN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (172, 'Polônia, Republica da', 'PL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (173, 'Portugal', 'PT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (174, 'Porto Rico', 'PR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (175, 'Catar', 'QA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (176, 'Reunião, Ilha', 'RE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (177, 'Romênia', 'RO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (178, 'Rússia, Federação da', 'RU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (179, 'Ruanda', 'RW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (180, 'São Cristovão e Neves, Ilhas', 'KN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (181, 'Santa Lucia', 'LC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (182, 'São Vicente e Granadinas', 'VC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (183, 'Samoa', 'WS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (184, 'San Marino', 'SM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (185, 'São Tome e Príncipe, Ilhas', 'ST')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (186, 'Arábia Saudita', 'SA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (187, 'Senegal', 'SN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (188, 'Seychelles', 'SC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (189, 'Serra Leoa', 'SL')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (190, 'Cingapura', 'SG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (191, 'Eslovaca, Republica', 'SK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (192, 'Eslovênia, Republica da', 'SI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (193, 'Salomão, Ilhas', 'SB')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (194, 'Somalia', 'SO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (195, 'África do Sul', 'ZA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (196, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (197, 'Espanha', 'ES')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (198, 'Sri Lanka', 'LK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (199, 'Santa Helena', 'SH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (200, 'São Pedro e Miquelon', 'PM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (201, 'Sudão', 'SD')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (202, 'Suriname', 'SR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (203, 'Svalbard e Jan Mayen', 'SJ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (204, 'Eswatini', 'SZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (205, 'Suécia', 'SE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (206, 'Suíça', 'CH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (207, 'Síria, Republica Árabe da', 'SY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (208, 'Formosa (Taiwan)', 'TW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (209, 'Tadjiquistao, Republica do', 'TJ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (210, 'Tanzânia, Republica Unida da', 'TZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (211, 'Tailândia', 'TH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (212, 'Togo', 'TG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (213, 'Toquelau, Ilhas', 'TK')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (214, 'Tonga', 'TO')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (215, 'Trinidad e Tobago', 'TT')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (216, 'Tunísia', 'TN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (217, 'Turquia', 'TR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (218, 'Turcomenistão, Republica do', 'TM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (219, 'Turcas e Caicos, Ilhas', 'TC')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (220, 'Tuvalu', 'TV')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (221, 'Uganda', 'UG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (222, 'Ucrânia', 'UA')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (223, 'Emirados Árabes Unidos', 'AE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (224, 'Reino Unido', 'GB')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (225, 'Estados Unidos', 'US')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (226, 'Ilhas Menores Distantes dos Estados Unidos', 'UM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (227, 'Uruguai', 'UY')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (228, 'Uzbequistão, Republica do', 'UZ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (229, 'Vanuatu', 'VU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (230, 'Venezuela', 'VE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (231, 'Vietnã', 'VN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (232, 'Virgens, Ilhas (Britânicas)', 'VG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (233, 'Virgens, Ilhas (E.U.A.)', 'VI')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (234, 'Wallis e Futuna, Ilhas', 'WF')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (235, 'Saara Ocidental', 'EH')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (236, 'Iémen', 'YE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (237, 'Iugoslávia, República Fed. da', 'YU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (238, 'Zâmbia', 'ZM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (239, 'Zimbabue', 'ZW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (240, 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)', 'GG')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (241, 'Jersey, Ilha do Canal', 'JE')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (243, 'Man, Ilha de', 'IM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (246, 'Montenegro', 'ME')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (247, 'Republika Srbija', 'RS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (248, 'Sudao do Sul', 'SS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (249, 'Zona do Canal do Panamá', NULL)
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (252, 'Palestina', 'PS')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (253, 'Aland, Ilhas', 'AX')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (255, 'Curaçao', 'CW')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (256, 'São Martinho, Ilha de (Parte Holandesa)', 'SM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (258, 'Bonaire', 'AN')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (259, 'Antartica', 'AQ')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (260, 'Ilha Herad e Ilhas Macdonald', 'AU')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (261, 'São Bartolomeu', 'FR')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (262, 'São Martinho, Ilha de (Parte Francesa)', 'SM')
INSERT INTO PAI_pais (PAI_nu_id, PAI_ds_nome, PAI_ds_sigla) VALUES (263, 'Terras Austrais e Antárcticas Francesas', 'TF')

--
-- Indexes for table "pais"
--

ALTER TABLE pais
  ADD PRIMARY KEY (id);
